/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TextEditor;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.BoxLayout;
import javax.swing.InputMap;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author ZK
 */
public class TextFrame extends javax.swing.JFrame {

    /**
     * Creates new form TextFrame
     */
    public TextFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        fc = new JFileChooser();
        undo = new UndoManager();
        textIM = jTextArea1.getInputMap();
        textAM = jTextArea1.getActionMap();
        painter = new DefaultHighlighter.DefaultHighlightPainter(Color.yellow);
        
        FileNameExtensionFilter txtFilter = new FileNameExtensionFilter("Plain text", "txt");
        fc.setFileFilter(txtFilter);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Text Editor");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setLineWrap(true);
        jTextArea1.getDocument().addUndoableEditListener(undo);
        jScrollPane1.setViewportView(jTextArea1);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        
        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("File");
        Action NewFile = new AbstractAction("New File"){
            @Override
            public void actionPerformed(ActionEvent arg0){

            }
        };

        Action OpenFile = new AbstractAction("Open File"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                if(fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
                    openFile(fc.getSelectedFile().getAbsolutePath());
                }
            }
        };

        Action SaveFile = new AbstractAction("Save File"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                saveFile();
            }
        };

        Action Exit = new AbstractAction("Exit"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                dispose();
            }
        };
        
        Action NewWindow = new AbstractAction("New Window"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                new TextFrame().setVisible(true);
            }
        };
        jMenuBar1.add(jMenu1);
        jMenu1.add(NewWindow);
        jMenu1.add(NewFile);
        jMenu1.add(OpenFile);
        jMenu1.add(SaveFile);
        jMenu1.add(Exit);
        
        jMenu2.setText("Edit");

        Action Copy = new AbstractAction("Copy"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                String s = jTextArea1.getSelectedText();
                StringSelection ss = new StringSelection(s);
                Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
                cb.setContents(ss, null);
            }
        };
        textIM.put(KeyStroke.getKeyStroke("control C"), "copy");
        textAM.put("copy", Copy);

        Action Paste = new AbstractAction("Paste"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                jTextArea1.paste();
            }
        };
        textIM.put(KeyStroke.getKeyStroke("control V"), "Paste");
        textAM.put("Paste",Paste);

        Action Cut = new AbstractAction("Cut"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                String s = jTextArea1.getSelectedText();
                StringSelection ss = new StringSelection(s);
                Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
                cb.setContents(ss, null);
                jTextArea1.setText(jTextArea1.getText().replace(s, ""));
            }
        };
        textIM.put(KeyStroke.getKeyStroke("control X"), "cut");
        textAM.put("cut", Cut);
        
        Action Undo = new AbstractAction("Undo"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                try {
                    if(undo.canUndo()){
                        undo.undo();
                    }
                } catch (CannotUndoException e) {
                    
                }
            }
        };
        textIM.put(KeyStroke.getKeyStroke("control Z"), "undo");
        textAM.put("undo", Undo);

        Action Redo = new AbstractAction("Redo"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                try {
                    if(undo.canRedo()){
                        undo.redo();
                    }
                } catch (CannotRedoException e) {
                    
                }
            }
        };
        textIM.put(KeyStroke.getKeyStroke("control Y"), "redo");
        textAM.put("redo", Redo);
        
        Action Find = new AbstractAction("Find"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                JPanel panel = new JPanel();
                panel.add(new JLabel("Find"));
                JTextField inputField = new JTextField(20);
                panel.add(inputField);
                Object[] options = {"Find next", "Quit"};
                int result = JOptionPane.showOptionDialog(null, panel, "Find", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
                String search = null;
                if(result == 0) search = inputField.getText();
                if(search != null){
                    jTextArea1.setCaretPosition(0);
                    int caret = jTextArea1.getCaretPosition();
                    String text = jTextArea1.getText().toLowerCase();
                    while(result == 0) {
                        try {
                            search = inputField.getText();
                            caret = text.indexOf(search, caret);
                            if(caret == -1) JOptionPane.showMessageDialog(null, "Can't find further", "Not Found", JOptionPane.WARNING_MESSAGE);
                            jTextArea1.getHighlighter().addHighlight(caret, caret+search.length(), painter);
                            caret += search.length();
                        } catch (BadLocationException e){

                        }
                        result = JOptionPane.showOptionDialog(null, panel, "Find", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
                    }
                    panel.removeAll();
                    jTextArea1.getHighlighter().removeAllHighlights();
                }

            }
        };
        textIM.put(KeyStroke.getKeyStroke("control F"), "find");
        textAM.put("find", Find);

        Action FindReplace = new AbstractAction("Find and Replace"){
            @Override
            public void actionPerformed(ActionEvent arg0){
                JPanel panel = new JPanel();
                panel.add(new JLabel("Find"));
                JTextField inputField = new JTextField(20);
                panel.add(inputField);
                panel.add(new JLabel("Replace with"));
                JTextField outputField = new JTextField(20);
                panel.add(outputField);
                Object[] options = {"Replace next", "Quit"};
                int result = JOptionPane.showOptionDialog(null, panel, "Find", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, null);
                String search = null;
                String output = null;
                if(result == 0) {
                    search = inputField.getText();
                    output = outputField.getText();
                }
                int caret;
                String text = jTextArea1.getText().toLowerCase();
                while(result == 0) {
                    try {
                        search = inputField.getText();
                        caret = text.indexOf(search);
                        if(caret == -1) JOptionPane.showMessageDialog(null, "Can't find further", "Not Found", JOptionPane.WARNING_MESSAGE);
                        jTextArea1.select(caret, caret + search.length());
                        jTextArea1.replaceSelection(output);
                        text = jTextArea1.getText().toLowerCase();
                    } catch (IllegalArgumentException e){

                    }
                    result = JOptionPane.showOptionDialog(null, panel, "Find", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, null);
                }
                panel.removeAll();
            }
        };

        jMenuBar1.add(jMenu2);
        jMenu2.add(Copy);
        jMenu2.add(Paste);
        jMenu2.add(Cut);
        jMenu2.add(Undo);
        jMenu2.add(Redo);
        jMenu2.add(Find);
        jMenu2.add(FindReplace);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }
    
    // METHODS
    private void openFile(String fileName){
        FileReader fr = null;
        try {
            fr = new FileReader(fileName);
            jTextArea1.read(fr, null);
            fr.close();
            setTitle(fileName);
        } catch (IOException e){
            e.printStackTrace();
        }
    }
    
    private void saveFile(){
        if(fc.showSaveDialog(null) == JFileChooser.APPROVE_OPTION){
            FileWriter fw = null;
            try {
                fw = new FileWriter(fc.getSelectedFile().getAbsolutePath());
                jTextArea1.write(fw);
                fw.close();
            } catch (IOException e){
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextFrame().setVisible(true);
            }
        });
    }

    
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private JFileChooser fc;
    private UndoManager undo;
    private InputMap textIM;
    private ActionMap textAM;
    private Highlighter.HighlightPainter painter;
}
